import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/Components/Navbar';
import Header from '@/Components/Header';
import Hero from '@/Components/Hero';
import Blockquote from '@/Components/Blockquote';
import Slider from '@/Components/Slider';
import Footer from '@/Components/Footer';
import Service from '@/Components/Service';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme = "light">
      <body className={inter.className}>
        <Header/>
        <Navbar />
        <Hero />
        <Blockquote/> 
        <Slider/>
        <Service/>
        <Footer/>
        {children}
        
        </body>
    </html>
  )
}
