import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from '@/Components/Nav';
import Header from '@/Components/Header';

import Footer from '@/Components/Footer';

import Navbar from '@/Components/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme = "light">
      <body className={inter.className}>
        <Header/>
        <Nav/> 
       
        
        
        {children}
        <Footer/>
        </body>
    </html>
  )
}
